/**
 * Ghost Seat — pure card model (WP1).
 *
 * A standard 52-card deck expressed as two-character codes, plus the position
 * math that makes "play by physical position" work: the ghost's photo fixes a
 * left-to-right order for their physical packet, and the station announces
 * every played card as "▶ Q♠ — 5th from the left" so the handler can pull it
 * face-down without ever seeing the hand.
 *
 * **Pure module.** No DOM, no Firestore, no `window`/`document` — not even at
 * import time. It is required directly by Jest's node environment and by
 * `node -e` smoke checks, and loaded in the browser via a plain <script> tag
 * (the site has no bundler and no ES modules).
 *
 * Card codes are `<rank><suit>`, exactly two characters, `T` for ten:
 * `AS KH QD 2C TS`. **The UI always displays `10`, never `T`** — use
 * `display()` for anything a human reads.
 *
 * Trump/ranking rules and which card beats which are deliberately out of
 * scope: the table adjudicates tricks. This module only lets a card be
 * identified, ordered, and transmitted unambiguously.
 */
const Cards = (() => {
    /** Canonical suit order — drives `sortBySuit` grouping and rank tiebreaks. */
    const SUITS = ['S', 'H', 'D', 'C'];

    /** Canonical rank order, strongest first. `T` = ten. */
    const RANKS = ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'];

    /** Suit code → display symbol. */
    const SUIT_SYMBOLS = { S: '♠', H: '♥', D: '♦', C: '♣' };

    /** Suit code → ink colour. Spades/Clubs black, Hearts/Diamonds red. */
    const SUIT_COLORS = { S: 'black', H: 'red', D: 'red', C: 'black' };

    /**
     * Access-code charset: 31 characters with every look-alike removed —
     * no I, L, O, 0, 1. Codes are read off a phone screen and typed on
     * another phone, so ambiguity costs more than entropy does.
     */
    const CODE_CHARSET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

    /** Length of a generated access code, in characters. */
    const CODE_LENGTH = 6;

    // Index lookups so the sorts stay O(n log n) with cheap comparisons.
    const SUIT_INDEX = SUITS.reduce((m, s, i) => { m[s] = i; return m; }, {});
    const RANK_INDEX = RANKS.reduce((m, r, i) => { m[r] = i; return m; }, {});

    /**
     * All 52 codes, in canonical order: suit-major (S H D C), rank-descending
     * (A K Q J T 9 … 2) within each suit.
     */
    const DECK = (() => {
        const out = [];
        for (const suit of SUITS) {
            for (const rank of RANKS) out.push(rank + suit);
        }
        return out;
    })();

    // ─── Code predicates & accessors ───────────────────────────────────────

    /**
     * Is `code` a well-formed card code?
     *
     * **Strict by design — lowercase is rejected.** Codes are generated by this
     * module and by tap-entry UI, never typed by a human, so there is no
     * ergonomic case for accepting `as`. Rejecting it means a stray lowercase
     * value surfaces as a validation error at the entry boundary instead of
     * silently failing an `indexOf` deep inside the position math.
     *
     * @param {*} code Candidate card code.
     * @returns {boolean} True only for a 2-char string with a valid uppercase
     *   rank and a valid uppercase suit.
     */
    function isValidCode(code) {
        if (typeof code !== 'string' || code.length !== 2) return false;
        return RANK_INDEX[code[0]] !== undefined && SUIT_INDEX[code[1]] !== undefined;
    }

    /**
     * Suit character of a card code.
     * @param {*} code Card code.
     * @returns {string|null} `'S'|'H'|'D'|'C'`, or null if `code` is invalid.
     */
    function suitOf(code) {
        return isValidCode(code) ? code[1] : null;
    }

    /**
     * Rank character of a card code (`T` for ten — not the display form).
     * @param {*} code Card code.
     * @returns {string|null} One of `RANKS`, or null if `code` is invalid.
     */
    function rankOf(code) {
        return isValidCode(code) ? code[0] : null;
    }

    /**
     * Human-facing rendering of a card code.
     *
     * The only place `T` becomes `10`; every UI surface must go through here
     * rather than printing the raw code.
     *
     * @param {*} code Card code, e.g. `'TH'`.
     * @returns {{rank: string, suit: string, color: string}|null} e.g.
     *   `{ rank: '10', suit: '♥', color: 'red' }`, or null if `code` is invalid.
     */
    function display(code) {
        if (!isValidCode(code)) return null;
        const rank = code[0];
        const suit = code[1];
        return {
            rank: rank === 'T' ? '10' : rank,
            suit: SUIT_SYMBOLS[suit],
            color: SUIT_COLORS[suit],
        };
    }

    /**
     * Human-readable label for a card, used inside error strings.
     * Falls back to a JSON-ish rendering for invalid input so the offending
     * value is still identifiable in the message.
     * @param {*} code Card code or junk.
     * @returns {string}
     */
    function label(code) {
        const d = display(code);
        if (d) return d.rank + d.suit;
        if (typeof code === 'string') return `"${code}"`;
        return String(code);
    }

    // ─── Hand validation ───────────────────────────────────────────────────

    /**
     * Validate a digitised hand: an array of exactly 13 valid, distinct codes.
     *
     * All independent problems accumulate — a 14-card hand containing a
     * duplicate and a junk code reports three errors, so the ghost fixes
     * everything in one pass instead of one error per retry.
     *
     * @param {*} cards Candidate hand (expected: array of card codes).
     * @returns {{ok: boolean, errors: string[]}} `ok` is true only when
     *   `errors` is empty.
     */
    function validateHand(cards) {
        const errors = [];

        if (!Array.isArray(cards)) {
            return { ok: false, errors: ['Hand must be an array of 13 card codes.'] };
        }

        if (cards.length !== 13) {
            errors.push(`Hand must contain exactly 13 cards (got ${cards.length}).`);
        }

        const invalid = cards.filter((c) => !isValidCode(c));
        if (invalid.length) {
            errors.push(`Not a valid card code: ${invalid.map(label).join(', ')}.`);
        }

        const seen = new Set();
        const dupes = [];
        for (const c of cards) {
            if (!isValidCode(c)) continue;
            if (seen.has(c)) {
                if (!dupes.includes(c)) dupes.push(c);
            } else {
                seen.add(c);
            }
        }
        if (dupes.length) {
            errors.push(`Duplicate card: ${dupes.map(label).join(', ')}.`);
        }

        return { ok: errors.length === 0, errors };
    }

    // ─── Sorting (display only — never touches photo order) ────────────────

    /**
     * Copy of `cards` keeping only well-formed codes. Sorting junk would put
     * it in an arbitrary slot; dropping it keeps the sorts total.
     * @param {*} cards Candidate array.
     * @returns {string[]}
     */
    function validOnly(cards) {
        return Array.isArray(cards) ? cards.filter(isValidCode) : [];
    }

    /**
     * Sort into suit groups (S H D C), rank-descending inside each group.
     *
     * Display convenience for the ghost's Arrange screen. It never affects the
     * photo-order positions used for physical retrieval.
     *
     * @param {*} cards Card codes.
     * @returns {string[]} A **new** array; the input is not mutated.
     */
    function sortBySuit(cards) {
        return validOnly(cards).sort((a, b) => (
            (SUIT_INDEX[a[1]] - SUIT_INDEX[b[1]]) || (RANK_INDEX[a[0]] - RANK_INDEX[b[0]])
        ));
    }

    /**
     * Sort by rank (A K Q J T 9 … 2), using suit order (S H D C) as tiebreak.
     *
     * @param {*} cards Card codes.
     * @returns {string[]} A **new** array; the input is not mutated.
     */
    function sortByRank(cards) {
        return validOnly(cards).sort((a, b) => (
            (RANK_INDEX[a[0]] - RANK_INDEX[b[0]]) || (SUIT_INDEX[a[1]] - SUIT_INDEX[b[1]])
        ));
    }

    // ─── Position math (the heart of play-by-position) ─────────────────────

    /**
     * The cards still physically in the packet, in photo order.
     *
     * Photo order = entry order = the physical left-to-right order of the
     * face-down fan, so this array *is* the packet as the handler will count
     * across it.
     *
     * Tolerant on both sides: a played card that was never in the hand is
     * ignored (a digitise typo repaired by undo must not corrupt positions),
     * and null/undefined inputs degrade to empty rather than throwing —
     * this runs against live Firestore docs where `cards` is null until the
     * ghost confirms.
     *
     * @param {string[]|null|undefined} cardsPhotoOrder The 13 codes in photo order.
     * @param {string[]|null|undefined} playedCards Codes already played.
     * @returns {string[]} New array, photo order preserved. `[]` for a null hand.
     */
    function remainingHand(cardsPhotoOrder, playedCards) {
        if (!Array.isArray(cardsPhotoOrder)) return [];
        const played = Array.isArray(playedCards) ? playedCards : [];
        // Counted rather than Set-based so a duplicated entry in `playedCards`
        // removes at most as many copies as the hand actually holds.
        const toRemove = new Map();
        for (const c of played) toRemove.set(c, (toRemove.get(c) || 0) + 1);

        const out = [];
        for (const c of cardsPhotoOrder) {
            const n = toRemove.get(c) || 0;
            if (n > 0) { toRemove.set(c, n - 1); continue; }
            out.push(c);
        }
        return out;
    }

    /**
     * 1-based position of `card` among the cards still held, in photo order —
     * the number the station announces ("▶ Q♠ — 5th from the left").
     *
     * Worked example: photo order `['AS','KH','QS','2C','9D']`, played
     * `['KH']` → the packet is now `['AS','QS','2C','9D']`, so
     * `positionOf('QS', …)` is **2**.
     *
     * @param {string} card The card to locate.
     * @param {string[]|null|undefined} cardsPhotoOrder The 13 codes in photo order.
     * @param {string[]|null|undefined} playedCards Codes already played.
     * @returns {number|null} 1-based position, or null if `card` is not among
     *   the remaining cards (already played, or never held).
     */
    function positionOf(card, cardsPhotoOrder, playedCards) {
        const remaining = remainingHand(cardsPhotoOrder, playedCards);
        const idx = remaining.indexOf(card);
        return idx === -1 ? null : idx + 1;
    }

    /**
     * 1-based position an **undone** card slides back into — the number the
     * station announces on a take-back ("↩ Q♠ taken back — slide it back 5th
     * from the left").
     *
     * Semantics: `card` is the entry being popped off `playedCards` (in the
     * live flow, its last entry). The answer is its `positionOf` computed
     * against `playedCards` **with that one entry removed** — i.e. the packet
     * as it will be *after* the undo, including the returning card itself.
     * Callers therefore pass `playedCards` as it stands *before* the pop, and
     * this function does the removal; passing an already-popped array yields
     * the same answer, since removing an absent entry is a no-op.
     *
     * Only one occurrence is removed (the last), so the arithmetic still holds
     * in the pathological case of a duplicated entry.
     *
     * Example: photo order `['AS','KH','QS','2C','9D']`, played
     * `['QS','KH']`, undoing `'KH'` → played becomes `['QS']`, the packet
     * becomes `['AS','KH','2C','9D']`, so the answer is **2**.
     *
     * @param {string} card The card being taken back.
     * @param {string[]|null|undefined} cardsPhotoOrder The 13 codes in photo order.
     * @param {string[]|null|undefined} playedCards Played codes, before the pop.
     * @returns {number|null} 1-based reinsert position, or null if `card` is
     *   not part of this hand at all.
     */
    function reinsertPosition(card, cardsPhotoOrder, playedCards) {
        const played = Array.isArray(playedCards) ? playedCards.slice() : [];
        const last = played.lastIndexOf(card);
        if (last !== -1) played.splice(last, 1);
        return positionOf(card, cardsPhotoOrder, played);
    }

    // ─── Access codes ──────────────────────────────────────────────────────

    /**
     * Build a 6-character access code from injected randomness.
     *
     * The caller supplies the entropy — `crypto.getRandomValues(new Uint8Array(6))`
     * in the browser — which keeps this function pure and therefore testable:
     * the same bytes always produce the same code. Never `Math.random`.
     *
     * Note on modulo bias: 256 is not a multiple of 31, so the first 8
     * characters of the charset are marginally more likely than the rest.
     * This is **explicitly acceptable** — the code gates a friends' league
     * card game against a teammate glancing at a phone, not an attacker, and
     * rejection sampling would buy nothing at these stakes.
     *
     * @param {number[]|Uint8Array} randomBytes Exactly 6 byte values.
     * @returns {string} A 6-character code drawn from `CODE_CHARSET`.
     * @throws {Error} If `randomBytes` is not array-like of length 6.
     */
    function generateAccessCode(randomBytes) {
        const isArrayLike = randomBytes
            && typeof randomBytes.length === 'number'
            && typeof randomBytes !== 'string';
        if (!isArrayLike) {
            throw new Error('generateAccessCode requires an array-like of 6 byte values.');
        }
        if (randomBytes.length !== CODE_LENGTH) {
            throw new Error(
                `generateAccessCode requires exactly ${CODE_LENGTH} byte values `
                + `(got ${randomBytes.length}).`
            );
        }
        let out = '';
        for (let i = 0; i < CODE_LENGTH; i++) {
            // >>> 0 then modulo: tolerates plain arrays with negative/float junk
            // the same way a Uint8Array would have coerced it.
            const byte = Math.abs(Math.trunc(Number(randomBytes[i]))) || 0;
            out += CODE_CHARSET[byte % CODE_CHARSET.length];
        }
        return out;
    }

    // ─── Query-string helper ───────────────────────────────────────────────

    /**
     * Parse a `location.search` string into a flat key → value object.
     *
     * Pattern (and implementation) taken verbatim from
     * `js/components/spectatorPass.js:44-56`, which is the source of truth for
     * URL-flag handling in this codebase. It lives here so `ghostGate.js` can
     * parse `?ghost=&seat=` without depending on the Spectator Pass component
     * or duplicating the parser a third time.
     *
     * Leading `?` optional; valueless keys (`?a&b=1`) yield `''`; empty
     * segments from `&&` are skipped; keys and values are URI-decoded.
     *
     * @param {string} search e.g. `'?ghost=abc&seat=t1_0'`.
     * @returns {Object<string,string>} `{}` for empty/non-string input.
     */
    function parseQuery(search) {
        if (!search || typeof search !== 'string') return {};
        const s = search.startsWith('?') ? search.slice(1) : search;
        const out = {};
        for (const pair of s.split('&')) {
            if (!pair) continue;
            const eq = pair.indexOf('=');
            const k = decodeURIComponent(eq < 0 ? pair : pair.slice(0, eq));
            const v = eq < 0 ? '' : decodeURIComponent(pair.slice(eq + 1));
            if (k) out[k] = v;
        }
        return out;
    }

    return {
        // Constants
        SUITS,
        RANKS,
        DECK,
        SUIT_SYMBOLS,
        SUIT_COLORS,
        CODE_CHARSET,
        CODE_LENGTH,
        // Codes
        isValidCode,
        suitOf,
        rankOf,
        display,
        // Hands
        validateHand,
        sortBySuit,
        sortByRank,
        // Position math
        remainingHand,
        positionOf,
        reinsertPosition,
        // Misc
        generateAccessCode,
        parseQuery,
    };
})();

if (typeof module !== 'undefined' && module.exports) {
    module.exports = Cards;
}
