/**
 * Season Facts Board — the "Season Records" wall on the Stats page.
 *
 * Renders the static pack generated by scripts/season-facts.js. Deliberately
 * dumb: no computation, no network, no key. The numbers were verified at
 * generation time, so this layer only has to lay them out and escape them.
 *
 * Degrades to nothing if js/data/seasonFacts.js has not been generated yet —
 * the Stats page renders exactly as it does today.
 */
const SeasonFactsBoard = (() => {
    function escape(s) {
        return String(s)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
    }

    function pack() {
        return (typeof SeasonFacts !== 'undefined' && SeasonFacts) ? SeasonFacts : null;
    }

    // "2026-08-15T…" → "15 Aug 2026". Kept local so the board has no
    // dependency on DateUtils' match-oriented formatting.
    function formatDate(iso) {
        const d = new Date(iso);
        if (isNaN(d)) return '';
        return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
    }

    // How many cards show before the reader has to ask for more. The board sits
    // between the leaderboard and the H2H matrix, so dumping 28 cards pushes the
    // rest of the page off-screen — the first batch has to earn the click.
    const PAGE_SIZE = 8;

    // ─── Fresh tails on every load ───────────────────────────────────────────
    // The FACTS are fixed — they are records, and a record that changes is a
    // bug. The Hinglish tail is not a fact, so it is re-picked at render time:
    // same numbers, different joke, every reload.
    //
    // The pack ships `intent` per fact (and a baked `tail`), so this degrades
    // cleanly: no ComedyLibrary on the page → the stored tail is used and the
    // board looks exactly as it did at generation time.
    //
    // One ledger per render keeps the no-repeat guarantee within a page:
    // 28 facts still get 28 distinct tails, just a different 28 each time.
    let _ledger = null;

    function freshTail(fact) {
        if (typeof ComedyLibrary === 'undefined') return fact.tail || null;
        if (!_ledger) _ledger = [];
        const pool = ComedyLibrary.candidates(fact.intent || 'quiet_round', {
            usedIds: _ledger,
            maxIntensity: roastIntensity(),
            limit: 99,
        });
        if (!pool.length) return fact.tail || null;
        // Math.random here is deliberate — reload-to-reload variety is the
        // whole feature. The generator stays seeded so the committed pack is
        // reproducible; only the display rotates.
        const chosen = pool[Math.floor(Math.random() * pool.length)] || pool[0];
        _ledger.push(chosen.id);
        return chosen.text;
    }

    // Reader-controlled sharpness, remembered across reloads. Falls back to the
    // intensity the pack was generated at, then to normal banter.
    function roastIntensity() {
        try {
            const saved = Number(localStorage.getItem('seasonFacts.roast'));
            if (saved >= 1 && saved <= 3) return saved;
        } catch (e) { /* storage blocked — use the default */ }
        const packed = Number(pack()?.roastIntensity);
        return (packed >= 1 && packed <= 3) ? packed : 2;
    }

    function setRoastIntensity(level) {
        try { localStorage.setItem('seasonFacts.roast', String(level)); }
        catch (e) { /* non-fatal */ }
    }

    // The Hinglish tail is rendered as its own element rather than being baked
    // into the sentence, so it can be styled (and, later, hidden) separately.
    // See claude/commentary-style.md §9: English body, Hindi landing.
    function renderCard(fact) {
        const t = freshTail(fact);
        const tail = t
            ? `<span class="sf-tail" lang="hi-Latn">${escape(t)}</span>`
            : '';
        return `
            <li class="sf-card${fact.ai ? ' sf-card-ai' : ''}">
                <span class="sf-icon" aria-hidden="true">${escape(fact.icon)}</span>
                <div class="sf-body">
                    <span class="sf-label">${escape(fact.label)}</span>
                    <p class="sf-text">${escape(fact.text)} ${tail}</p>
                </div>
            </li>
        `;
    }

    function mount(hostId = 'seasonFactsBoard') {
        const host = document.getElementById(hostId);
        if (!host) return;

        const data = pack();
        if (!data || !Array.isArray(data.facts) || !data.facts.length) {
            host.innerHTML = '';
            return;
        }

        const c = data.coverage || {};
        const aiCount = data.facts.filter(f => f.ai).length;

        // The provenance line is the point of the whole feature: these are
        // records off the real archive, not invented colour.
        const meta = [
            c.matches ? `${c.matches} matches` : '',
            c.rounds ? `${c.rounds} rounds` : '',
            data.generatedAt ? `updated ${formatDate(data.generatedAt)}` : '',
        ].filter(Boolean).join(' · ');

        const facts = data.facts;
        // A fresh ledger per mount: this render's 28 tails are distinct from
        // each other, but unrelated to the last render's.
        _ledger = null;

        host.innerHTML = `
            <div class="stats-card season-facts-card">
                <div class="sf-head">
                    <h3>📜 Season Records &amp; Facts</h3>
                    ${aiCount ? '<span class="sf-badge">AI ✨</span>' : ''}
                    ${typeof ComedyLibrary !== 'undefined' ? `
                        <button type="button" id="sfShuffleBtn" class="sf-shuffle-btn"
                                title="Naye taane — same facts, new endings">🎲</button>
                    ` : ''}
                </div>
                <p class="card-hint">Computed from every round ever played${meta ? ` · ${escape(meta)}` : ''}.</p>
                <ul class="sf-grid">
                    ${facts.slice(0, PAGE_SIZE).map(renderCard).join('')}
                </ul>
                ${facts.length > PAGE_SIZE ? `
                    <div class="sf-more-row">
                        <button type="button" id="sfMoreBtn" class="sf-more-btn">
                            Aur Dikhao Bhai, Majaa aa raha h — ${facts.length - PAGE_SIZE} baaki
                        </button>
                    </div>
                ` : ''}
            </div>
        `;

        wireMore(host, facts);
        wireShuffle(host, facts);
    }

    // Reroll every visible tail in place. Keeps how many cards are open — the
    // reader asked for more facts, not for the list to collapse.
    function wireShuffle(host, facts) {
        const btn = host.querySelector('#sfShuffleBtn');
        if (!btn) return;

        btn.addEventListener('click', () => {
            const grid = host.querySelector('.sf-grid');
            if (!grid) return;
            const open = grid.querySelectorAll('.sf-card').length || PAGE_SIZE;

            _ledger = null;                       // a whole new set of jokes
            grid.innerHTML = facts.slice(0, open).map(renderCard).join('');

            btn.classList.remove('sf-shuffle-spin');
            void btn.offsetWidth;                 // restart the animation
            btn.classList.add('sf-shuffle-spin');
        });
    }

    // Reveal the next page on click. Re-labels itself with what is left, and
    // collapses to a "bas, itna hi tha" note once everything is shown.
    function wireMore(host, facts) {
        const btn = host.querySelector('#sfMoreBtn');
        if (!btn) return;

        let shown = PAGE_SIZE;
        btn.addEventListener('click', () => {
            const grid = host.querySelector('.sf-grid');
            const next = facts.slice(shown, shown + PAGE_SIZE);
            if (!grid || !next.length) return;

            grid.insertAdjacentHTML('beforeend', next.map(renderCard).join(''));
            shown += next.length;

            const left = facts.length - shown;
            if (left > 0) {
                btn.textContent = `Aur Dikhao Bhai, Majaa aa raha h — ${left} baaki`;
            } else {
                // Nothing left to reveal: retire the button rather than leave a
                // dead control on the page.
                const row = btn.parentElement;
                btn.remove();
                if (row) row.innerHTML = '<span class="sf-more-done">Bas, itne hi the.</span>';
            }
        });
    }

    return {
        mount, pack, PAGE_SIZE,
        // Exposed so the console (or a future settings row) can dial the
        // sharpness without a rebuild: SeasonFactsBoard.setRoastIntensity(3).
        roastIntensity, setRoastIntensity,
        freshTail,
    };
})();

if (typeof module !== 'undefined' && module.exports) {
    module.exports = SeasonFactsBoard;
}
